const $=id=>document.getElementById(id),KEY='cabinet-sene-v3',OLD='cabinet-sene-v2',PRICE=50;
const defaults=['Mohamed','Ghadi','Khetri','Ahmedou','Mbay'];
let editEntry=null,editWithdrawal=null,currentMonth=monthKey(new Date()),toastTimer,state=load();
function num(v){v=Number(String(v??'').replace(',','.'));return Number.isFinite(v)?v:0}
function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(v){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(num(v))}
function normalize(x={}){return{workers:Array.isArray(x.workers)?x.workers.map((w,i)=>({id:String(w.id??`w${i}`),name:String(w.name||'Médecin'),active:w.active!==false})):[],entries:Array.isArray(x.entries)?x.entries.filter(e=>e?.date&&e?.doctorId).map(e=>({id:String(e.id??`s${Date.now()}${Math.random()}`),date:String(e.date),doctorId:String(e.doctorId),consultations:Math.max(0,Math.floor(num(e.consultations))),notes:String(e.notes||'')})):[],withdrawals:Array.isArray(x.withdrawals)?x.withdrawals.filter(w=>w?.date&&w?.doctorId&&num(w.amount)>0).map(w=>({id:String(w.id??`r${Date.now()}${Math.random()}`),date:String(w.date),doctorId:String(w.doctorId),amount:Math.round(num(w.amount)*100)/100,notes:String(w.notes||'')})):[]}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x)return normalize(x)}catch(_){}const fresh={workers:defaults.map((name,i)=>({id:`w${i+1}`,name,active:true})),entries:[],withdrawals:[]};try{const x=JSON.parse(localStorage.getItem(OLD));if(x?.workers&&x?.entries){fresh.workers=x.workers;fresh.entries=x.entries.map(e=>({id:e.id,date:e.date,doctorId:e.doctorId,consultations:num(e.consultations),notes:e.notes||''}));x.entries.forEach(e=>{if(num(e.taken)>0)fresh.withdrawals.push({id:`legacy-${e.id}`,date:e.date,doctorId:e.doctorId,amount:num(e.taken),notes:'Retrait migré'})})}}catch(_){}return normalize(fresh)}
function save(){localStorage.setItem(KEY,JSON.stringify(state));if($('saveStatus'))$('saveStatus').textContent='Enregistré · '+new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}
function workers(){return state.workers.filter(w=>w.active)}
function doctor(id){return state.workers.find(w=>String(w.id)===String(id))}
function entries(){return state.entries.filter(e=>e.date.startsWith(currentMonth)).sort((a,b)=>b.date.localeCompare(a.date))}
function withdrawals(){return state.withdrawals.filter(w=>w.date.startsWith(currentMonth)).sort((a,b)=>b.date.localeCompare(a.date))}
function generated(c){return Math.max(0,Math.floor(num(c)))*PRICE}
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),1800)}
function options(){const html='<option value="">Choisir un médecin</option>'+workers().map(w=>`<option value="${esc(w.id)}">${esc(w.name)}</option>`).join('');['entryDoctor','withdrawalDoctor'].forEach(id=>{const s=$(id);if(!s)return;const old=s.value;s.innerHTML=html;if(workers().some(w=>w.id===old))s.value=old})}
function render(){if($('monthPicker'))$('monthPicker').value=currentMonth;options();const es=entries(),ws=withdrawals(),consult=es.reduce((s,e)=>s+num(e.consultations),0),gen=consult*PRICE,taken=ws.reduce((s,w)=>s+num(w.amount),0);$('summaryConsultations').textContent=fmt(consult);$('summaryGenerated').textContent=fmt(gen);$('summaryTaken').textContent=fmt(taken);$('summaryBalance').textContent=fmt(gen-taken);renderEntries(es);renderWithdrawals(ws);renderStats(es,ws);renderWorkersCount()}
function dateParts(d){const x=new Date(`${d}T12:00:00`);return[x.toLocaleDateString('fr-FR',{day:'2-digit'}),x.toLocaleDateString('fr-FR',{month:'short'}).replace('.','')]}
function renderEntries(es){$('entriesCount').textContent=`${es.length} ${es.length===1?'saisie':'saisies'}`;$('entriesList').innerHTML=es.length?es.map(e=>{const [day,mon]=dateParts(e.date);return`<article class="entry-item"><div class="entry-date">${day}<small>${mon}</small></div><div class="entry-main"><strong>${esc(doctor(e.doctorId)?.name||'Médecin')}</strong><p>${fmt(e.consultations)} consultations × ${PRICE} MRU${e.notes?` · ${esc(e.notes)}`:''}</p><div class="entry-actions"><button type="button" class="mini-btn" data-ee="${esc(e.id)}"><i class="fa-solid fa-pen"></i> Modifier</button><button type="button" class="mini-btn danger" data-de="${esc(e.id)}"><i class="fa-solid fa-trash"></i> Supprimer</button></div></div><div class="entry-values"><strong>${fmt(generated(e.consultations))} MRU</strong><small>Généré</small></div></article>`}).join(''):'<div class="empty-state">Aucune saisie pour ce mois.<br>Ajoutez la première avec « Nouvelle saisie ».</div>'}
function renderWithdrawals(ws){$('withdrawalsCount').textContent=`${ws.length} ${ws.length===1?'retrait':'retraits'}`;$('withdrawalsList').innerHTML=ws.length?ws.map(w=>{const [day,mon]=dateParts(w.date);return`<article class="entry-item"><div class="entry-date">${day}<small>${mon}</small></div><div class="entry-main"><strong>${esc(doctor(w.doctorId)?.name||'Médecin')}</strong><p>${esc(w.notes||'Retrait')}</p><div class="entry-actions"><button type="button" class="mini-btn" data-ew="${esc(w.id)}"><i class="fa-solid fa-pen"></i> Modifier</button><button type="button" class="mini-btn danger" data-dw="${esc(w.id)}"><i class="fa-solid fa-trash"></i> Supprimer</button></div></div><div class="entry-values"><strong>${fmt(w.amount)} MRU</strong><small>Retiré</small></div></article>`}).join(''):'<div class="empty-state">Aucun retrait pour ce mois.</div>'}
function renderStats(es,ws){const list=workers().map(w=>{const c=es.filter(e=>e.doctorId===w.id).reduce((s,e)=>s+num(e.consultations),0),t=ws.filter(x=>x.doctorId===w.id).reduce((s,x)=>s+num(x.amount),0);return{w,c,g:c*PRICE,t}}),max=Math.max(1,...list.map(x=>x.c));$('doctorStats').innerHTML=list.length?list.map(x=>`<div class="doctor-stat"><div class="doctor-stat-head"><strong>${esc(x.w.name)}</strong><span>${fmt(x.c)}</span></div><small>${fmt(x.g)} MRU générés · ${fmt(x.t)} MRU retirés</small><div class="bar"><i style="width:${x.c?Math.max(5,x.c/max*100):0}%"></i></div></div>`).join(''):'<div class="empty-state">Aucun médecin actif.</div>'}
function renderWorkersCount(){const e=$('workersCount');if(e){const n=workers().length;e.textContent=`${n} actif${n>1?'s':''}`}}
function preview(){if($('entryGenerated'))$('entryGenerated').value=generated($('entryConsultations').value)}
function resetEntry(){editEntry=null;$('entryForm').reset();$('entryDate').value=new Date().toISOString().slice(0,10);$('entryDialogTitle').textContent='Nouvelle saisie';options();preview()}
function openEntry(){if(!workers().length){toast('Ajoutez d’abord un médecin');return openWorkers()}resetEntry();$('entryDialog').showModal()}
function closeEntry(){if($('entryDialog').open)$('entryDialog').close()}
function submitEntry(e){e.preventDefault();const date=$('entryDate').value,doctorId=$('entryDoctor').value,c=Math.max(0,Math.floor(num($('entryConsultations').value)));if(!date)return toast('Choisissez une date');if(!doctorId)return toast('Choisissez un médecin');const data={date,doctorId,consultations:c,notes:$('entryNotes').value.trim()};if(editEntry){const i=state.entries.findIndex(x=>x.id===editEntry);if(i<0)return toast('Saisie introuvable');state.entries[i]={...state.entries[i],...data}}else state.entries.push({id:`s${Date.now()}-${Math.random().toString(36).slice(2,6)}`,...data});currentMonth=date.slice(0,7);const wasEdit=!!editEntry;editEntry=null;save();closeEntry();render();toast(wasEdit?'Saisie modifiée':'Saisie enregistrée')}
function editE(id){const x=state.entries.find(e=>e.id===id);if(!x)return toast('Saisie introuvable');editEntry=id;options();$('entryDate').value=x.date;$('entryDoctor').value=x.doctorId;$('entryConsultations').value=x.consultations;$('entryNotes').value=x.notes;$('entryDialogTitle').textContent='Modifier la saisie';preview();$('entryDialog').showModal()}
function deleteE(id){if(!confirm('Supprimer cette saisie ?'))return;state.entries=state.entries.filter(e=>e.id!==id);save();render();toast('Saisie supprimée')}
function resetWithdrawal(){editWithdrawal=null;$('withdrawalForm').reset();$('withdrawalDate').value=new Date().toISOString().slice(0,10);$('withdrawalDialogTitle').textContent='Nouveau retrait';options()}
function openWithdrawal(){if(!workers().length){toast('Ajoutez d’abord un médecin');return openWorkers()}resetWithdrawal();$('withdrawalDialog').showModal()}
function closeWithdrawal(){if($('withdrawalDialog').open)$('withdrawalDialog').close()}
function submitWithdrawal(e){e.preventDefault();const date=$('withdrawalDate').value,doctorId=$('withdrawalDoctor').value,amount=Math.round(num($('withdrawalAmount').value)*100)/100;if(!date)return toast('Choisissez une date');if(!doctorId)return toast('Choisissez un médecin');if(amount<=0)return toast('Montant invalide');const data={date,doctorId,amount,notes:$('withdrawalNotes').value.trim()};if(editWithdrawal){const i=state.withdrawals.findIndex(x=>x.id===editWithdrawal);if(i<0)return toast('Retrait introuvable');state.withdrawals[i]={...state.withdrawals[i],...data}}else state.withdrawals.push({id:`r${Date.now()}-${Math.random().toString(36).slice(2,6)}`,...data});currentMonth=date.slice(0,7);const wasEdit=!!editWithdrawal;editWithdrawal=null;save();closeWithdrawal();render();toast(wasEdit?'Retrait modifié':'Retrait enregistré')}
function editW(id){const x=state.withdrawals.find(w=>w.id===id);if(!x)return toast('Retrait introuvable');editWithdrawal=id;options();$('withdrawalDate').value=x.date;$('withdrawalDoctor').value=x.doctorId;$('withdrawalAmount').value=x.amount;$('withdrawalNotes').value=x.notes;$('withdrawalDialogTitle').textContent='Modifier le retrait';$('withdrawalDialog').showModal()}
function deleteW(id){if(!confirm('Supprimer ce retrait ?'))return;state.withdrawals=state.withdrawals.filter(w=>w.id!==id);save();render();toast('Retrait supprimé')}
function changeMonth(d){const [y,m]=currentMonth.split('-').map(Number);currentMonth=monthKey(new Date(y,m-1+d,1));render()}
function openWorkers(){renderWorkers();$('workersDialog').showModal()}
function closeWorkers(){if($('workersDialog').open)$('workersDialog').close()}
function renderWorkers(){$('workersList').innerHTML=workers().length?workers().map(w=>`<div class="worker-item"><input class="worker-name" data-rn="${esc(w.id)}" value="${esc(w.name)}"><button type="button" class="danger-btn" data-rm="${esc(w.id)}"><i class="fa-solid fa-trash"></i></button></div>`).join(''):'<div class="empty-state">Aucun médecin actif.</div>';renderWorkersCount()}
function addWorker(){const e=$('newWorkerName'),name=e.value.trim();if(!name)return toast('Saisissez un nom');if(workers().some(w=>w.name.toLowerCase()===name.toLowerCase()))return toast('Ce médecin existe déjà');state.workers.push({id:`w${Date.now()}`,name,active:true});e.value='';save();renderWorkers();render();toast('Médecin ajouté')}
function removeWorker(id){const w=doctor(id);if(!w)return;if(!confirm(`Retirer ${w.name} de la liste ?`))return;w.active=false;save();renderWorkers();render()}
function renameWorker(id,name){const w=doctor(id),n=name.trim();if(w&&n){w.name=n;save();render()}}
function excelDate(s){const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function exportData(){if(typeof XLSX==='undefined')return alert('Le module Excel n’a pas pu être chargé.');const shifts=[...state.entries].sort((a,b)=>a.date.localeCompare(b.date)).map(e=>({Date:excelDate(e.date),Travailleur:doctor(e.doctorId)?.name||'Médecin',Consultations:num(e.consultations),'Prix/consultation (MRU)':PRICE,'Total généré (MRU)':generated(e.consultations),Remarque:e.notes||''})),ws=[...state.withdrawals].sort((a,b)=>a.date.localeCompare(b.date)).map(w=>({Date:excelDate(w.date),Travailleur:doctor(w.doctorId)?.name||'Médecin','Montant retiré (MRU)':num(w.amount),Remarque:w.notes||''}));const tc=shifts.reduce((s,r)=>s+r.Consultations,0),tg=shifts.reduce((s,r)=>s+r['Total généré (MRU)'],0),tw=ws.reduce((s,r)=>s+r['Montant retiré (MRU)'],0);shifts.push({Date:'',Travailleur:'TOTAL',Consultations:tc,'Prix/consultation (MRU)':'','Total généré (MRU)':tg,Remarque:''});ws.push({Date:'',Travailleur:'TOTAL','Montant retiré (MRU)':tw,Remarque:''});const wb=XLSX.utils.book_new(),a=XLSX.utils.json_to_sheet(shifts),b=XLSX.utils.json_to_sheet(ws),c=XLSX.utils.json_to_sheet([{Indicateur:'Total consultations',Valeur:tc},{Indicateur:'Prix par consultation (MRU)',Valeur:PRICE},{Indicateur:'Total généré (MRU)',Valeur:tg},{Indicateur:'Total retiré (MRU)',Valeur:tw},{Indicateur:'Solde (MRU)',Valeur:tg-tw}]);a['!cols']=[{wch:13},{wch:24},{wch:15},{wch:23},{wch:20},{wch:42}];b['!cols']=[{wch:13},{wch:24},{wch:22},{wch:42}];XLSX.utils.book_append_sheet(wb,a,'Saisies');XLSX.utils.book_append_sheet(wb,b,'Retraits');XLSX.utils.book_append_sheet(wb,c,'Résumé');XLSX.writeFile(wb,`cabinet-sene-${new Date().toISOString().slice(0,10)}.xlsx`);toast('Excel exporté')}
function bind(){$('entryConsultations').addEventListener('input',preview);$('openEntryBtn').addEventListener('click',openEntry);$('fabEntryBtn').addEventListener('click',openEntry);$('entryForm').addEventListener('submit',submitEntry);$('closeEntryBtn').addEventListener('click',closeEntry);$('cancelEntryBtn').addEventListener('click',closeEntry);$('openWithdrawalBtn').addEventListener('click',openWithdrawal);$('openWithdrawalBtn2').addEventListener('click',openWithdrawal);$('withdrawalForm').addEventListener('submit',submitWithdrawal);$('closeWithdrawalBtn').addEventListener('click',closeWithdrawal);$('cancelWithdrawalBtn').addEventListener('click',closeWithdrawal);$('entriesList').addEventListener('click',e=>{const a=e.target.closest('[data-ee]'),b=e.target.closest('[data-de]');if(a)editE(a.dataset.ee);if(b)deleteE(b.dataset.de)});$('withdrawalsList').addEventListener('click',e=>{const a=e.target.closest('[data-ew]'),b=e.target.closest('[data-dw]');if(a)editW(a.dataset.ew);if(b)deleteW(b.dataset.dw)});$('prevMonthBtn').addEventListener('click',()=>changeMonth(-1));$('nextMonthBtn').addEventListener('click',()=>changeMonth(1));$('monthPicker').addEventListener('change',e=>{if(e.target.value){currentMonth=e.target.value;render()}});$('manageWorkersBtn').addEventListener('click',openWorkers);$('addDoctorQuickBtn').addEventListener('click',openWorkers);$('closeWorkersBtn').addEventListener('click',closeWorkers);$('addWorkerBtn').addEventListener('click',addWorker);$('newWorkerName').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addWorker()}});$('workersList').addEventListener('click',e=>{const b=e.target.closest('[data-rm]');if(b)removeWorker(b.dataset.rm)});$('workersList').addEventListener('change',e=>{if(e.target.dataset.rn)renameWorker(e.target.dataset.rn,e.target.value)});$('exportBtn').addEventListener('click',exportData)}
bind();resetEntry();resetWithdrawal();render();save();